import org.jetbrains.gradle.ext.Gradle

plugins {
    id 'com.diffplug.spotless' version '6.19.0' apply false
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.4.1'
    id 'com.gtnewhorizons.retrofuturagradle' version '2.0.3' apply false
    id 'net.darkhax.curseforgegradle' version '1.+' apply false
    id 'com.modrinth.minotaur' version '2.+' apply false
    id 'org.jetbrains.changelog' version '2.5.0' apply false
    id 'com.gradleup.shadow' version '9.6.+' apply false
}

apply from: 'gradle/scripts/helpers.gradle'

// Early Assertions
assertProperty 'mod_version'
assertProperty 'root_package'
assertProperty 'mod_id'
assertProperty 'mod_name'

assertSubProperties 'use_tags', 'tag_class_name'
assertSubProperties 'use_access_transformer', 'access_transformer_locations'
assertSubProperties 'use_mixins', 'mixin_booter_version', 'mixin_refmap'
assertSubProperties 'is_coremod', 'coremod_includes_mod', 'coremod_plugin_class_name'
assertSubProperties 'use_asset_mover', 'asset_mover_version'

setDefaultProperty 'generate_sources_jar', true, false
setDefaultProperty 'generate_javadocs_jar', true, false
setDefaultProperty 'mapping_channel', true, 'stable'
setDefaultProperty 'mapping_version', true, '39'
setDefaultProperty 'use_dependency_at_files', true, true
setDefaultProperty 'minecraft_username', true, 'Developer'
setDefaultProperty 'extra_jvm_args', false, ''
setDefaultProperty 'extra_tweak_classes', false, ''
setDefaultProperty 'change_minecraft_sources', false, false
setDefaultProperty 'publish_to_curseforge', true, false
setDefaultProperty 'mixin_connector_class', false, ''

ext {
    modVersion = propertyString('mod_version')
    modGroup = propertyString('root_package')
    minecraftVersion = propertyString('minecraftVersion')
    xplatResources = { -> rootProject.file('xplat/src/main/resources') }
}

subprojects {
    group = rootProject.ext.modGroup

    ext.mavenVersion = rootProject.ext.modVersion
    if (System.getenv("RELEASE") == null) {
        ext.mavenVersion += "-SNAPSHOT"
    }
    ext.mavenVersion += "+${rootProject.ext.minecraftVersion}"
    version = "${ext.mavenVersion}+${rootProject.property('enabled_platforms')}"

    repositories {
        maven {
            name 'CleanroomMC Maven'
            url 'https://maven.cleanroommc.com'
        }
        exclusiveContent {
            forRepository {
                maven {
                    name 'CleanroomMC CurseMaven'
                    url 'https://curse.cleanroommc.com'
                }
            }
            filter {
                includeGroup 'curse.maven'
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name 'Modrinth'
                    url 'https://api.modrinth.com/maven'
                }
            }
            filter {
                includeGroup 'maven.modrinth'
            }
        }
        maven {
            name = "Spongepowered"
            url = "https://repo.spongepowered.org/repository/maven-public/"
        }
        maven {
            name = "blamejared"
            url = "https://maven.blamejared.com/"
        }
        mavenLocal()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    plugins.withId('java') {
        if (project.hasProperty('enable_junit_testing') && propertyBool('enable_junit_testing')) {
            dependencies {
                testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
                testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
            }
        }
    }
}

idea {
    project {
        settings {
            runConfigurations {
                "0. Setup Decomp Workspace"(Gradle) {
                    taskNames = [":forge:setupDecompWorkspace"]
                }
                "1. Run Client"(Gradle) {
                    taskNames = [":forge:runClient"]
                }
                "2. Run Server"(Gradle) {
                    taskNames = [":forge:runServer"]
                }
                "3. Run Obfuscated Client"(Gradle) {
                    taskNames = [":forge:runObfClient"]
                }
                "4. Run Obfuscated Server"(Gradle) {
                    taskNames = [":forge:runObfServer"]
                }
            }
            compiler.javac {
                javacAdditionalOptions = "-encoding utf8"
            }
            gradle.projectsEvaluated {
                idea.project.settings.compiler.javac.moduleJavacAdditionalOptions = subprojects.collectEntries { p ->
                    [(p.name + ".main"): p.tasks.named('compileJava').get().options.compilerArgs.collect { '"' + it + '"' }.join(' ')]
                }
            }
        }
    }
}
