org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.12.2
enabled_platforms=forge

archives_base_name=emi
mod_version=1.1.24-beta.4
maven_group=dev.emi

architectury_version=4.9.83

loom.platform=forge

mapping_version=39

forge_version=1.12.2-14.23.5.2847

jei_version=jei_1.12.2:4.16.5.1029
hei_version=4.34.3

access_transformer_locations=emi_at.cfg

mixin_booter_version=10.7
mixin_configs=emi.mixins.json emi-forge.mixins.json
mixin_package=dev.emi.emi.mixin
mixin_refmap=mixins.emi.refmap.json

coremod_plugin_class_name=com.rewindmc.retroemi.plugin.REMILoadingPlugin
