org.gradle.jvmargs=-Xmx3G

minecraft_version=1.7.10
enabled_platforms=forge

archives_base_name=emi
mod_version=1.1.24-beta.4
maven_group=dev.emi

loom.platform=legacyforge

mapping_version=12

forge_version=1.7.10-10.13.4.1614-1.7.10

raven_build=1
sparrow_build=1
nests_build=2

gtnhlib_version=0.11.30
waila_version=1.19.30
nei_version=2.8.114-GTNH
mobs_info_version=0.5.3-GTNH

access_transformer_locations=emi_at.cfg

unimixins_version=0.3.1
mixinconbooter_version=1.3
mixin_configs=emi.mixins.json
mixin_package=dev.emi.emi.mixin
mixin_refmap=mixins.emi.refmap.json

coremod_plugin_class_name=dev.emi.emi.mixinsupport.REMIEarlyMixins
