pluginManagement {
    repositories {
	    maven { url "https://repo.spongepowered.org/repository/maven-public/" }
	    maven {url "https://nexus.gtnewhorizons.com/repository/public/"}
	    maven { url "https://maven.cleanroommc.com" }
	    maven { url "https://curse.cleanroommc.com" }
	    maven { url "https://api.modrinth.com/maven" }
        gradlePluginPortal()
    }
}

plugins {
    // Automatic toolchain provisioning
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}

include("xplat")
include("forge")

rootProject.name = "emi"
