import com.gtnewhorizons.retrofuturagradle.mcp.InjectTagsTask
import net.darkhax.curseforgegradle.TaskPublishCurseForge
import org.jetbrains.changelog.Changelog
import org.jetbrains.gradle.ext.Gradle

buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath 'com.modrinth.minotaur:Minotaur:2.4.3'
		classpath 'gradle.plugin.com.matthewprenger:CurseGradle:1.4.0'
	}
}

plugins {
	id 'java'
	id 'java-library'
	id 'maven-publish'
	id 'org.jetbrains.gradle.plugin.idea-ext'
	id 'com.gtnewhorizons.retrofuturagradle'
	id 'com.gradleup.shadow'
	id 'org.jetbrains.changelog'
}
if (System.getenv("MODRINTH_TOKEN")) {
	apply plugin: "com.modrinth.minotaur"
}
if (System.getenv("CURSEFORGE_TOKEN")) {
	apply plugin: "com.matthewprenger.cursegradle"
}
evaluationDependsOn ':xplat'

apply from: rootProject.file('gradle/scripts/helpers.gradle')
apply from: rootProject.file('gradle/scripts/minecraft-base.gradle')

tasks.decompressDecompiledSources.enabled !propertyBool('change_minecraft_sources') || !layout.buildDirectory.dir('rfg/minecraft-src').get().asFile.exists()

minecraft {
	// Add various JVM arguments here for runtime
	def args = ['-ea:' + rootProject.group]
	args << '-Dfml.coreMods.load=' + propertyString('coremod_plugin_class_name')
	args << '-Dmixin.hotSwap=true'
	args << '-Dmixin.checks.interfaces=true'
	args << '-Dmixin.debug.export=true'
	extraRunJvmArguments.addAll(args)
	extraRunJvmArguments.addAll(propertyStringList('extra_jvm_args'))

	def tagsFile = rootProject.file('tags.properties')
	if (tagsFile.exists()) {
		Properties props = new Properties().tap { it.load(tagsFile.newInputStream()); it }
		if (!props.isEmpty()) {
			injectedTags.set(props.collectEntries { k, v ->
					def interpolated = interpolate(v)
					if (interpolated == null || interpolated.isEmpty()) throw new GradleException("Empty tag value found for key: $k")
					[(k): interpolated]
			})
		}
	}
}

dependencies {
	implementation project(':xplat')

}

apply from: rootProject.file('gradle/scripts/dependencies.gradle')

['runClient', 'runServer', 'runObfClient', 'runObfServer'].each { taskName ->
	tasks.named(taskName, JavaExec).configure { JavaExec task ->
		task.doFirst {
			if (task.debug) {
				task.jvmArgs("-javaagent:${configurations.mixinAgent.singleFile.absolutePath}")
			}
		}
	}
}

jar {
	// Merge the platform-neutral code (incl. the generated mixin refmap)
	from project(':xplat').sourceSets.main.output

	manifest {
		def attribute_map = [:]
		attribute_map['FMLCorePlugin'] = propertyString('coremod_plugin_class_name')
		attribute_map['FMLCorePluginContainsFMLMod'] = true
		def currentTasks = gradle.startParameter.taskNames
		if (currentTasks[0] == 'build' || currentTasks[0] == 'prepareObfModsFolder' || currentTasks[0] == 'runObfClient') {
			attribute_map['ForceLoadAsMod'] = true
		}
		attribute_map['FMLAT'] = propertyString('access_transformer_locations')
		attribute_map['MixinConfigs'] = propertyString('mixin_configs')
		attributes(attribute_map)
	}
}

idea {
	module {
		inheritOutputDirs = true
	}
}

compileTestJava {
	sourceCompatibility = targetCompatibility = 8
}

test {
	useJUnitPlatform()
	javaLauncher.set(javaToolchains.launcherFor {
		languageVersion = JavaLanguageVersion.of(8)
	})
	if (propertyBool('show_testing_output')) {
		testLogging {
			showStandardStreams = true
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	if (it.name in ['compileMcLauncherJava', 'compilePatchedMcJava']) {
		return
	}
	sourceCompatibility = 17
	options.release.set(8)
	javaCompiler.set(javaToolchains.compilerFor {
		languageVersion.set(JavaLanguageVersion.of(16))
		vendor.set(JvmVendorSpec.AZUL)
	})
}

tasks.register('cleanroomAfterSync') {
	group 'cleanroom helpers'
	dependsOn 'injectTags', 'generateMixinJson'
}

tasks.withType(Javadoc).configureEach {
	sourceCompatibility = 17
}

tasks.named('injectTags', InjectTagsTask).configure {
	onlyIf {
		return !it.getTags().get().isEmpty()
	}
	it.outputClassName.set(propertyString('tag_class_name'))
}

tasks.named('prepareObfModsFolder').configure {
	finalizedBy 'prioritizeCoremods'
}

tasks.register('prioritizeCoremods') {
	dependsOn 'prepareObfModsFolder'
	doLast {
		fileTree('run/obfuscated').forEach {
			if (it.isFile() && it.name =~ '(mixinbooter|configanytime)(-)([0-9])+\\.+([0-9])+(.jar)') {
				it.renameTo(new File(it.parentFile, "!${it.name}"))
			}
		}
	}
}

if (propertyBool('publish_to_curseforge')) {
	assertProperty 'curseforge_project_id'
	apply plugin: 'net.darkhax.curseforgegradle'
	tasks.register('curseforge', TaskPublishCurseForge) {
		group 'publishing'
		description "Uploads CurseForge project ${propertyString('curseforge_project_id')}"
	}
}

tasks.register('generateTemplates') {
}

apply from: rootProject.file('gradle/scripts/publishing.gradle')
apply from: rootProject.file('gradle/scripts/extra.gradle')
