import net.darkhax.curseforgegradle.TaskPublishCurseForge

buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath 'com.modrinth.minotaur:Minotaur:2.4.3'
		classpath 'gradle.plugin.com.matthewprenger:CurseGradle:1.4.0'
	}
}

plugins {
	id 'java'
	id 'java-library'
	id 'maven-publish'
	id 'org.jetbrains.gradle.plugin.idea-ext'
	id 'gg.essential.loom'
	id 'com.gradleup.shadow'
	id 'org.jetbrains.changelog'
}
if (System.getenv("MODRINTH_TOKEN")) {
	apply plugin: "com.modrinth.minotaur"
}
if (System.getenv("CURSEFORGE_TOKEN")) {
	apply plugin: "com.matthewprenger.cursegradle"
}
evaluationDependsOn ':xplat'

apply from: rootProject.file('gradle/scripts/helpers.gradle')

loom {
	forge {
		pack200Provider = new dev.architectury.pack200.java.Pack200Adapter()
		accessTransformer(rootProject.file("xplat/src/main/resources/${propertyString('access_transformer_locations')}"))
		accessTransformer(provider {
			zipTree(configurations.jeiAt.singleFile).matching { include 'META-INF/jei_at.cfg' }.singleFile
		})
	}
	mixin {
		defaultRefmapName.set(propertyString('mixin_refmap'))
	}
	runs {
		client {
			property('fml.coreMods.load', propertyString('coremod_plugin_class_name'))
			programArgs('--mixin', propertyString('mixin_configs'))
		}
		server {
			property('fml.coreMods.load', propertyString('coremod_plugin_class_name'))
			programArgs('--mixin', propertyString('mixin_configs'))
		}
	}
}

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(16))
		vendor.set(JvmVendorSpec.AZUL)
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings "de.oceanlabs.mcp:mcp_stable:${propertyString('mapping_version')}-1.12"
	forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

	modCompileOnly "mezz.jei:${jei_version}"

	implementation project(':xplat')

	annotationProcessor 'com.github.bsideup.jabel:jabel-javac-plugin:1.0.0'
	annotationProcessor 'net.java.dev.jna:jna-platform:5.13.0'
}

sourceSets.main.output.resourcesDir = file('build/classes/java/main')

processResources {
	from project(':xplat').sourceSets.main.output.classesDirs
	from project(':xplat').tasks.named('processResources')
}

apply from: rootProject.file('gradle/scripts/dependencies.gradle')

jar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	from project(':xplat').sourceSets.main.output

	manifest {
		def attribute_map = [:]
		attribute_map['FMLCorePlugin'] = propertyString('coremod_plugin_class_name')
		attribute_map['FMLCorePluginContainsFMLMod'] = true
		attribute_map['FMLAT'] = propertyString('access_transformer_locations')
		attribute_map['MixinConfigs'] = propertyString('mixin_configs')
		attributes(attribute_map)
	}
}

idea {
	module {
		inheritOutputDirs = true
	}
}

tasks.withType(JavaCompile).configureEach {
	sourceCompatibility = 17
	options.release.set(8)
	javaCompiler.set(javaToolchains.compilerFor {
		languageVersion.set(JavaLanguageVersion.of(16))
		vendor.set(JvmVendorSpec.AZUL)
	})
}

tasks.withType(Javadoc).configureEach {
	sourceCompatibility = 17
}

tasks.withType(JavaExec).configureEach {
	javaLauncher.set(javaToolchains.launcherFor {
		languageVersion.set(JavaLanguageVersion.of(8))
		vendor.set(JvmVendorSpec.AZUL)
	})
}

configurations {
	devMods
	jeiAt
}

dependencies {
	devMods 'zone.rong:mixinbooter:10.7'
	jeiAt "mezz.jei:${jei_version}"
}

tasks.register('devMods', Copy) {
	from configurations.devMods
	into file('run/mods')
}

tasks.named('runClient') { dependsOn 'devMods' }
tasks.named('runServer') { dependsOn 'devMods' }

if (propertyBool('publish_to_curseforge')) {
	assertProperty 'curseforge_project_id'
	apply plugin: 'net.darkhax.curseforgegradle'
	tasks.register('curseforge', TaskPublishCurseForge) {
		group 'publishing'
		description "Uploads CurseForge project ${propertyString('curseforge_project_id')}"
	}
}

apply from: rootProject.file('gradle/scripts/publishing.gradle')
apply from: rootProject.file('gradle/scripts/extra.gradle')
